apiVersion: v2
name: ai-chatbot-framework
description: AI Chatbot Framework - Parent Chart
type: application
version: 1.0.0

appVersion: "1.0.0.1"
dependencies:
  - name: backend
    version: "1.0.0"
    repository: "file://charts/backend"
    condition: backend.enabled
  - name: frontend
    version: "1.0.0"
    repository: "file://charts/frontend"
    condition: frontend.enabled
