apiVersion: v1
kind: Secret
metadata:
  name: prod-cluster
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: cluster
type: Opaque
stringData:
  name: prod-cluster
  server: https://prod-cluster-endpoint.eks.us-east-1.amazonaws.com
  config: |
    {
      "bearerToken": "",
      "tlsClientConfig": {
        "insecure": false,
        "caData": ""
      },
      "awsAuthConfig": {
        "clusterName": "prod-cluster",
        "roleARN": "arn:aws:iam::333333333333:role/argocd-prod-cluster-role"
      }
    }

