apiVersion: v1
kind: Secret
metadata:
  name: staging-cluster
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: cluster
type: Opaque
stringData:
  name: staging-cluster
  server: https://staging-cluster-endpoint.eks.us-east-1.amazonaws.com
  config: |
    {
      "bearerToken": "",
      "tlsClientConfig": {
        "insecure": false,
        "caData": ""
      },
      "awsAuthConfig": {
        "clusterName": "staging-cluster",
        "roleARN": "arn:aws:iam::222222222222:role/argocd-staging-cluster-role"
      }
    }

